client_config_backend: settings
client_config:
  client_id: 245062948912-9is0a697in35mp68at4m7itsmbpvve1n.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install