# Generated by Django 5.0.1 on 2024-07-16 04:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200, verbose_name='HEADER')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%y', verbose_name='GAMBAR')),
                ('textarea', django_ckeditor_5.fields.CKEditor5Field(verbose_name='DESKRIPSI')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200, verbose_name='HEADER')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%y', verbose_name='GAMBAR')),
                ('textarea', django_ckeditor_5.fields.CKEditor5Field(verbose_name='DESKRIPSI')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
