# Generated by Django 5.0.1 on 2024-07-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainarticle',
            name='bigTitle',
            field=models.CharField(default=1, max_length=200, verbose_name='BIG TITLE'),
            preserve_default=False,
        ),
    ]
