# Generated by Django 5.0.1 on 2024-07-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_mainarticle_bigtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainarticle',
            name='author',
            field=models.CharField(default=1, max_length=50, verbose_name='HEADER'),
            preserve_default=False,
        ),
    ]
