# Generated by Django 5.0.1 on 2024-07-16 07:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_mainarticle_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200, verbose_name='HEADER')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%y', verbose_name='GAMBAR')),
                ('textarea', django_ckeditor_5.fields.CKEditor5Field(verbose_name='DESKRIPSI')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='author',
            field=models.CharField(max_length=50, verbose_name='AUTHOR'),
        ),
    ]
