# Generated by Django 5.0.1 on 2024-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_issue_alter_mainarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='../images/placeholder.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.FileField(blank=True, default='../images/placeholder.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='image',
            field=models.FileField(blank=True, default='../images/placeholder.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
    ]
