# Generated by Django 5.0.1 on 2024-07-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_image_alter_issue_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='placeholder.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.FileField(blank=True, default='placeholder.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='image',
            field=models.FileField(blank=True, default='placeholder.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
    ]
