# Generated by Django 5.0.1 on 2024-07-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_last_modified_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
    ]
