# Generated by Django 5.0.1 on 2024-08-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_rename_post_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='../static/images/DabestCard.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.FileField(blank=True, default='../static/images/DabestCard.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='image',
            field=models.FileField(blank=True, default='../static/images/DabestCard.jpg', null=True, upload_to='images/%y', verbose_name='GAMBAR'),
        ),
    ]
