# Generated by Django 5.0.1 on 2024-05-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_project_latcoor_alter_project_longcoor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='namaPekerjaan',
            field=models.CharField(max_length=200, unique=True, verbose_name='NAMA PEKERJAAN'),
        ),
    ]
