# Generated by Django 5.0.1 on 2024-05-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_project_namapekerjaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='namaPekerjaan',
            field=models.CharField(max_length=200, verbose_name='NAMA PEKERJAAN'),
        ),
    ]
