# Generated by Django 5.0.1 on 2024-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_project_namapekerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='videoFile',
            field=models.FileField(null=True, upload_to='media/%y', verbose_name='VIDEO'),
        ),
    ]
