# Generated by Django 5.0.1 on 2024-05-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_project_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='videoFile',
            field=models.FileField(blank=True, null=True, upload_to='media/%y', verbose_name='VIDEO'),
        ),
    ]
