# Generated by Django 5.0.1 on 2024-05-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='department',
            field=models.CharField(choices=[('Research and Development', 'Research and Development'), ('Marketing & Communication', 'Marketing & Communication'), ('Project', 'Project')], max_length=200),
        ),
        migrations.AlterField(
            model_name='career',
            name='employeeType',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('INTERNSHIP/ PART TIME', 'INTERNSHIP/ PART TIME'), ('BY PROJECT', 'BY PROJECT')], max_length=200),
        ),
        migrations.AlterField(
            model_name='career',
            name='location',
            field=models.CharField(choices=[('Banda Aceh', ' Banda Aceh'), ('Langsa', ' Langsa'), ('Lhokseumawe', ' Lhokseumawe'), ('Sabang', ' Sabang'), ('Subulussalam', ' Subulussalam'), ('Denpasar', ' Denpasar'), ('Pangkalpinang', ' Pangkalpinang'), ('Cilegon', ' Cilegon'), ('Serang', ' Serang'), ('Tangerang Selatan', ' Tangerang Selatan'), ('Tangerang', ' Tangerang'), ('Bengkulu', ' Bengkulu'), ('Yogyakarta', ' Yogyakarta'), ('Gorontalo', ' Gorontalo'), ('Kota Administrasi Jakarta Barat', ' Kota Administrasi Jakarta Barat'), ('Kota Administrasi Jakarta Pusat', ' Kota Administrasi Jakarta Pusat'), ('Kota Administrasi Jakarta Selatan', ' Kota Administrasi Jakarta Selatan'), ('Kota Administrasi Jakarta Timur', ' Kota Administrasi Jakarta Timur'), ('Kota Administrasi Jakarta Utara', ' Kota Administrasi Jakarta Utara'), ('Sungai Penuh', ' Sungai Penuh'), ('Jambi', ' Jambi'), ('Bandung', ' Bandung'), ('Bekasi', ' Bekasi'), ('Bogor', ' Bogor'), ('Cimahi', ' Cimahi'), ('Cirebon', ' Cirebon'), ('Depok', ' Depok'), ('Sukabumi', ' Sukabumi'), ('Tasikmalaya', ' Tasikmalaya'), ('Banjar', ' Banjar'), ('Magelang', ' Magelang'), ('Pekalongan', ' Pekalongan'), ('Salatiga', ' Salatiga'), ('Semarang', ' Semarang'), ('Surakarta', ' Surakarta'), ('Tegal', ' Tegal'), ('Batu', ' Batu'), ('Blitar', ' Blitar'), ('Kediri', ' Kediri'), ('Madiun', ' Madiun'), ('Malang', ' Malang'), ('Mojokerto', ' Mojokerto'), ('Pasuruan', ' Pasuruan'), ('Probolinggo', ' Probolinggo'), ('Surabaya', ' Surabaya'), ('Pontianak', ' Pontianak'), ('Singkawang', ' Singkawang'), ('Banjarbaru', ' Banjarbaru'), ('Banjarmasin', ' Banjarmasin'), ('Palangka Raya', ' Palangka Raya'), ('Balikpapan', ' Balikpapan'), ('Bontang', ' Bontang'), ('Samarinda', ' Samarinda'), ('Nusantara', ' Nusantara'), ('Tarakan', ' Tarakan'), ('Batam', ' Batam'), ('Tanjungpinang', ' Tanjungpinang'), ('Bandar Lampung', ' Bandar Lampung'), ('Metro', ' Metro'), ('Ternate', ' Ternate'), ('Tidore Kepulauan', ' Tidore Kepulauan'), ('Ambon', ' Ambon'), ('Tual', ' Tual'), ('Bima', ' Bima'), ('Mataram', ' Mataram'), ('Kupang', ' Kupang'), ('Sorong', ' Sorong'), ('Jayapura', ' Jayapura'), ('Dumai', ' Dumai'), ('Pekanbaru', ' Pekanbaru'), ('Makassar', ' Makassar'), ('Palopo', ' Palopo'), ('Parepare', ' Parepare'), ('Palu', ' Palu'), ('Baubau', ' Baubau'), ('Kendari', ' Kendari'), ('Bitung', ' Bitung'), ('Kotamobagu', ' Kotamobagu'), ('Manado', ' Manado'), ('Tomohon', ' Tomohon'), ('Bukittinggi', ' Bukittinggi'), ('Padang', ' Padang'), ('Padang Panjang', ' Padang Panjang'), ('Pariaman', ' Pariaman'), ('Payakumbuh', ' Payakumbuh'), ('Sawahlunto', ' Sawahlunto'), ('Solok', ' Solok'), ('Lubuklinggau', ' Lubuklinggau'), ('Pagar Alam', ' Pagar Alam'), ('Palembang', ' Palembang'), ('Prabumulih', ' Prabumulih'), ('Binjai', ' Binjai'), ('Gunungsitoli', ' Gunungsitoli'), ('Medan', ' Medan'), ('Padangsidimpuan', ' Padangsidimpuan'), ('Pematangsiantar', ' Pematangsiantar'), ('Sibolga', ' Sibolga'), ('Tanjungbalai', ' Tanjungbalai'), ('Tebing Tinggi', ' Tebing Tinggi')], max_length=200),
        ),
    ]
