# Generated by Django 5.0.1 on 2024-05-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_career_department_alter_career_employeetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=100, verbose_name='TAGS')),
                ('headline', models.CharField(max_length=200, verbose_name='HEADER')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%y', verbose_name='GAMBAR')),
                ('textarea', models.TextField(max_length=500, verbose_name='DESKRIPSI')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
