# Generated by Django 5.0.1 on 2024-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputApplicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200, verbose_name='FIRST NAME')),
                ('LastName', models.CharField(max_length=200, verbose_name='LAST NAME')),
                ('Gender', models.CharField(max_length=20, verbose_name='JENIS KELAMIN')),
                ('DoB', models.DateField(verbose_name='TANGGAL LAHIR')),
                ('PoB', models.CharField(max_length=50, verbose_name='TEMPAT LAHIR')),
                ('Nationality', models.CharField(max_length=20, verbose_name='KEBANGSAAN')),
                ('personalEmail', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('countryCode', models.IntegerField(verbose_name='COUNTRY CODE')),
                ('personalMobile', models.IntegerField(max_length=20, verbose_name='PHONE NUMBER')),
                ('linkedin', models.CharField(max_length=254, verbose_name='LINKEDIN ID')),
                ('address_1', models.CharField(max_length=254, verbose_name='ADDRESS_1 ')),
                ('address_2', models.CharField(max_length=254, verbose_name='ADDRESS_2 ')),
                ('expectedSalary', models.IntegerField(verbose_name='salary')),
                ('grossSalary', models.IntegerField(verbose_name='gross salary')),
                ('medicalHistory', models.TextField(verbose_name='MEDICAL HISTORY')),
                ('ReferensiInfo', models.CharField(max_length=152, verbose_name='Referesni Info')),
                ('referensiName', models.CharField(max_length=152, verbose_name='Referesni Name')),
                ('referensiRelasi', models.CharField(max_length=152, verbose_name='Referesni Relasi')),
            ],
        ),
        migrations.CreateModel(
            name='UploadApplicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-createAt']},
        ),
    ]
