# Generated by Django 5.0.1 on 2024-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_uploadapplicant_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadapplicant',
            old_name='description',
            new_name='ApplicantName',
        ),
        migrations.AddField(
            model_name='uploadapplicant',
            name='jobPosition',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
