# Generated by Django 5.0.1 on 2024-06-11 02:32

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_description_uploadapplicant_applicantname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputapplicant',
            name='countryCode',
        ),
        migrations.AddField(
            model_name='inputapplicant',
            name='jobPosition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inputapplicant',
            name='ReferensiInfo',
            field=models.CharField(max_length=152, verbose_name='Referensi Info'),
        ),
        migrations.AlterField(
            model_name='inputapplicant',
            name='personalMobile',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='inputapplicant',
            name='referensiName',
            field=models.CharField(max_length=152, verbose_name='Referensi Name'),
        ),
        migrations.AlterField(
            model_name='inputapplicant',
            name='referensiRelasi',
            field=models.CharField(max_length=152, verbose_name='Referensi Relasi'),
        ),
    ]
