# Generated by Django 5.0.1 on 2024-06-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_inputapplicant_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputapplicant',
            name='LicDrive',
            field=models.CharField(choices=[('SIM A', 'SIM A'), ('SIM B', 'SIM B'), ('SIM C', 'SIM C')], default='1', max_length=5, verbose_name='DRIVING LICENSE'),
            preserve_default=False,
        ),
    ]
