# Generated by Django 5.0.1 on 2024-06-11 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_inputapplicant_licdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputapplicant',
            name='submit_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputapplicant',
            name='Nationality',
            field=models.CharField(choices=[('WNI', 'WNI'), ('WNA', 'WNA')], max_length=20, verbose_name='WARGA NEGARA'),
        ),
    ]
