# Generated by Django 5.0.1 on 2024-06-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_inputapplicant_submit_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobList', models.CharField(max_length=200)),
            ],
        ),
    ]
