# Generated by Django 5.0.1 on 2024-06-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_career_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departementlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
