# Generated by Django 5.0.1 on 2024-06-19 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_departementlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='department',
            field=models.ForeignKey(blank=True, default='Departement', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departementlist'),
        ),
    ]
