# Generated by Django 5.0.1 on 2024-06-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_career_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='main.departementlist'),
        ),
    ]
