# Generated by Django 5.0.1 on 2024-07-05 04:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_career_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empType', models.CharField(max_length=200, unique=True, verbose_name='EMPLOYEE TYPE')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='textarea',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='DESKRIPSI'),
        ),
        migrations.AlterField(
            model_name='career',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employeeType', to='main.employeetypelist', to_field='empType'),
        ),
    ]
