# Generated by Django 5.0.1 on 2024-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_career_employeetype_alter_career_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadapplicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reject', 'Reject'), ('Approve', 'Approve')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
