# Generated by Django 5.0.1 on 2024-07-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_approvedapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedApps',
            fields=[
                ('uploadapplicant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.uploadapplicant')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['approved_date'],
            },
            bases=('main.uploadapplicant',),
        ),
        migrations.DeleteModel(
            name='ApprovedApplicant',
        ),
    ]
