# Generated by Django 5.0.1 on 2024-07-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_approvedapps_delete_approvedapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.ManyToManyField(to='main.uploadapplicant')),
            ],
            options={
                'ordering': ['approved_date'],
            },
        ),
        migrations.DeleteModel(
            name='ApprovedApps',
        ),
    ]
