# Generated by Django 5.0.1 on 2024-07-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_approvedapplicant_delete_approvedapps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedApplicant',
        ),
    ]
