# Generated by Django 5.0.1 on 2024-07-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_delete_approvedapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedApplicant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.uploadapplicant',),
        ),
    ]
