# Generated by Django 5.0.1 on 2024-07-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rejectapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewApplicant',
            fields=[
            ],
            options={
                'verbose_name': 'Review Applicant',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.uploadapplicant',),
        ),
        migrations.AlterModelOptions(
            name='approvedapplicant',
            options={'verbose_name': '  Approve Applicant'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-posting_date'], 'verbose_name': 'Career List'},
        ),
        migrations.AlterModelOptions(
            name='employeetypelist',
            options={'verbose_name': 'Employee Type'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-createAt'], 'verbose_name': 'Journal'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='rejectapplicant',
            options={'verbose_name': ' Reject Applicant'},
        ),
        migrations.AlterModelOptions(
            name='uploadapplicant',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '   Pending Applicant'},
        ),
    ]
