# Generated by Django 5.0.1 on 2024-07-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_reviewapplicant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadapplicant',
            name='lampiranSKA',
            field=models.FileField(blank=True, null=True, upload_to='files/%y'),
        ),
    ]
