# Generated by Django 5.0.1 on 2024-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_uploadapplicant_lampiranska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadapplicant',
            name='klasifikasiSKA',
            field=models.CharField(blank=True, choices=[('', '--Silahkan Pilih--'), ('Muda', 'Muda'), ('Madya', 'Madya'), ('Utama', 'Utama')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='uploadapplicant',
            name='subklasifikasiSKA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
