# Generated by Django 5.0.1 on 2024-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_tag_remove_news_tags_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='main.tag'),
        ),
    ]
