# Generated by Django 5.0.1 on 2024-08-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_news_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
