# Generated by Django 5.0.1 on 2024-08-29 06:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_delete_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTag', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200, verbose_name='HEADER')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%y', verbose_name='GAMBAR')),
                ('textarea', django_ckeditor_5.fields.CKEditor5Field(verbose_name='DESKRIPSI')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='tags', to='main.activitytag')),
            ],
            options={
                'verbose_name': 'Activities',
                'ordering': ['-createAt'],
            },
        ),
    ]
