# Generated by Django 5.0.1 on 2024-08-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_activitytag_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Kegiatan',
        ),
        migrations.AlterModelOptions(
            name='kegiatan',
            options={'ordering': ['-createAt'], 'verbose_name': 'DABEST Activities'},
        ),
    ]
