# Generated by Django 5.0.1 on 2024-09-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_activity_kegiatan_alter_kegiatan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.PositiveIntegerField(default=0, verbose_name='JUMLAH IMPACT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ktPekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KATEGORI PEKERJAAN'),
        ),
        migrations.AddField(
            model_name='project',
            name='tahun',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='TAHUN PEKERJAAN'),
        ),
    ]
