# Generated by Django 5.0.1 on 2024-09-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_project_impact_project_ktpekerjaan_project_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unitImpact',
            field=models.CharField(blank=True, choices=[('Infrastruktur Pelabuhan', 'Infrastruktur Pelabuhan'), ('Jiwa Penduduk', 'Jiwa Penduduk'), ('Hektar Sawah', 'Hektar Sawah'), ('Hektar Permukiman yang terlindungi', 'Hektar Permukiman yang terlindungi'), ('Desain / Kajian', 'Desain / Kajian'), ('Hektar Lahan Konservasi', 'Hektar Lahan Konservasi')], max_length=100, null=True, verbose_name='UNIT IMPACT'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ktPekerjaan',
            field=models.CharField(blank=True, choices=[('Perencanaan Pesisir', 'Perencanaan Pesisir'), ('Pemanfaatan Sumber Daya Air', 'Pemanfaatan Sumber Daya Air'), ('Pengendalian Daya Rusak Air', 'Pengendalian Daya Rusak Air'), ('Konservasi', 'Konservasi'), ('Lain - Lain', 'Lain - Lain')], max_length=100, null=True, verbose_name='KATEGORI PEKERJAAN'),
        ),
    ]
